In [1]:
import numpy as np
import pandas as pd
import scipy.linalg as sla

In [2]:
# matrix left/right division (following MATLAB function naming)
_mldivide = lambda denom, numer: sla.lstsq(np.array(denom), np.array(numer))[0]
_mrdivide = lambda numer, denom: (sla.lstsq(np.array(denom).T, np.array(numer).T)[0]).T

gama = np.random.random((6, 3))
f = np.random.random((3, 30))
# cholesky decomposition
R1 = sla.cholesky(gama.T @ gama)

# singular value decomposition
R2, _, _ = sla.svd(R1@f@f.T@R1.T)

# matrix right division
gama_new = _mrdivide(gama, R1).dot(R2)
f_new = _mldivide(R2, R1.dot(f))

In [3]:
gama = np.random.random((6, 3))

In [4]:
f = np.random.random((3, 30))

In [5]:
# cholesky decomposition
R1 = sla.cholesky(gama.T @ gama)

# singular value decomposition
R2, _, _ = sla.svd(R1@f@f.T@R1.T)

# matrix right division
gama_new = _mrdivide(gama, R1).dot(R2)
f_new = _mldivide(R2, R1.dot(f))

In [9]:
R1

array([[1.55146848, 0.77453112, 1.18100732],
       [0.        , 1.20787767, 0.71242556],
       [0.        , 0.        , 0.50083141]])

In [7]:
gama_new.T@ gama_new

array([[ 1.00000000e+00, -1.96468190e-16, -2.79494988e-16],
       [-1.96468190e-16,  1.00000000e+00, -8.32128909e-16],
       [-2.79494988e-16, -8.32128909e-16,  1.00000000e+00]])

In [8]:
f_new@f_new.T

array([[ 1.30433490e+02, -8.88182810e-15,  4.68068227e-15],
       [-8.88182810e-15,  2.76518008e+00,  1.76516206e-15],
       [ 4.68068227e-15,  1.76516206e-15,  4.00041709e-01]])